* Current issues with McCLIM

This document outlines issues that I have had while developing the
Mastodon client using CLIM. In my opinion, these are fundamental
issues in that they are defects that a beginner would not expect to
have to manually create workarounds for.

Also, some of these issues doesn't even have reasonably easy
workarounds. In particular the image transformation issue.

** No word wrapping in application panes

Logged as bug [[https://github.com/robert-strandh/McCLIM/issues/249][249]]

** No word wrapping in TEXT-EDITOR

Logged as bug [[https://github.com/robert-strandh/McCLIM/issues/247][247]]

** Application panes should reflow when windows are resized

Logged as bug [[https://github.com/robert-strandh/McCLIM/issues/250][250]]

** Image transformations doesn't work at all

Logged as bug [[https://github.com/robert-strandh/McCLIM/issues/177][177]]

This one requires a bit more consideration. The spec does explicitly
say that the =:TRANSFORMATION= parameter is only used to affect the
position of the image, not its geometry. However, it could be argued
that the reason they said this was because at the time the spec was
written, computers were not fast enough to perform image
transformations in real time. This is not the case anymore.

If one were to stick with the spec's definition, then
=TRANSFORM-DESIGN= should be used, but there is no method to actually
draw a transformed design.

Thus it must be concluded that there is no way one can transform
images in McCLIM at all.

** When using INCREMENTAL-REDISPLAY, the pane doesn't resize correctly

Logged as bug [[https://github.com/robert-strandh/McCLIM/issues/251][251]]
** BOUNDING-RECTANGLE-WIDTH should not include the width of the scrollbar

Logged as bug [[https://github.com/robert-strandh/McCLIM/issues/254][254]]

This bug prevents a proper implementation of word wrapping, which
means that there is no simple workaround for [[No word wrapping in
application panes]]
